version: "3.7"
services:
  qdrant:
    image: qdrant/qdrant:v1.9.2
    ports:
      - "6333:6333"
      - "6334:6334" # grpc
    volumes:
      - qdrant-data:/qdrant/storage
  redis:
    image: redis:7-alpine
    ports:
      - 6397:6379
    volumes:
      - redis-data:/data
volumes:
  qdrant-data:
  redis-data:
